language: bash

sudo: required
dist: trusty

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install -y shellcheck
  - sudo sh -c "`curl -L https://raw.github.com/rylnd/shpec/master/install.sh`"

script: make
